events {}

http {

    server {

        listen 80;

        location /order {

            proxy_pass http://order-service:3000;

        }

        location /analyse {

            proxy_pass http://analyser-service:6000;

        }

    }

}